server:
  port: ${SERVER_PORT}

railwayThreads: ${RAILWAY_THREADS}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE}
      minimum-idle: ${HIKARI_MINIMIM_IDLE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}

